[package]
name = "astrolabe-weave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
astrolabe-domain.workspace = true
calyx-core.workspace = true
calyx-loom.workspace = true

[lib]
path = "src/lib.rs"

[dev-dependencies]
calyx-aster.workspace = true
