/*
 * env_store_config.h — Astrolabe-owned store configuration for libcbm (#240/#241).
 *
 * Two upstream contracts are broken on the Astrolabe host and are repaired here,
 * in Astrolabe-owned C compiled into libcbm.a. The vendored tree is never edited;
 * the build-local overlay generated by `patches/cbm/env_apply_store_patch.py`
 * calls into this translation unit.
 *
 * #240 — env-as-IPC does not work across the Rust/C boundary on Windows.
 *   Rust's `std::env::set_var` writes the Win32 environment block
 *   (`SetEnvironmentVariableW`); libcbm's `cbm_safe_getenv` walks the C runtime's
 *   `environ` array. Windows synchronises those two stores only for the
 *   environment a process *inherits* (MSDN: "getenv operates only on the data
 *   structures accessible to the run-time library and not on the environment
 *   'segment' created for the process by the operating system"). A runtime
 *   `set_var("CBM_CACHE_DIR", ...)` is therefore invisible to libcbm, which then
 *   resolves the store from `$HOME` with no error at all — a silent fallback.
 *   The repair is to stop using the environment as an IPC channel: the host
 *   passes the store location across the FFI boundary as a parameter, through
 *   `cbm_astro_set_cache_dir`, and `cbm_resolve_cache_dir` consults that explicit
 *   override before it ever looks at an environment variable.
 *
 * #241 — a resolver that can fail must not be consumed as if it cannot.
 *   `cbm_safe_getenv` `snprintf`s an environment value into a caller-sized buffer
 *   and discards the return value, so an over-long value is silently cut and the
 *   library then resolves a *different* store. Truncation is detected here and
 *   turned into a named, sticky, queryable fault carrying a
 *   {code, message, remediation} envelope. Callers (and the Rust host, through
 *   `cbm_astro_env_fault_code`) can refuse instead of guessing.
 *
 * Thread-safety: the fault record and the override buffer are guarded by an
 * `atomic_flag` spinlock. Readers return pointers to process-lifetime static
 * storage, which is the same contract the vendored resolvers already publish.
 */
#ifndef ASTROLABE_CBM_ENV_STORE_CONFIG_H
#define ASTROLABE_CBM_ENV_STORE_CONFIG_H

#include <stddef.h>

/*
 * Byte capacity of a CBM store path.
 *
 * Not a magic number: it is the size of the `static char buf[CBM_SZ_1K]` result
 * buffer that `cbm_resolve_cache_dir()` and `cbm_get_home_dir()` publish in
 * `cbm/src/foundation/platform.c`. A store path that does
 * not fit in that buffer cannot be represented by the library at all, so the only
 * honest answer is a coded refusal — never a truncated path to a different
 * directory. `scripts/test-cbm-env-store-patch.py` asserts this equals the
 * vendored `CBM_SZ_1K` enumerator, and `astrolabe-bridge` re-derives the same
 * bound from `constants.h`.
 */
#define CBM_ASTRO_STORE_PATH_CAP 1024

/* ── Explicit configuration across the FFI boundary (#240) ───────── */

/*
 * Point libcbm at `path` for every subsequent `cbm_resolve_cache_dir()`.
 *
 * This is the ONLY runtime-safe way to relocate the CBM store from the Rust
 * host: it crosses the boundary as a parameter, not as an environment variable,
 * so it is immune to the Win32/CRT environment divergence described above.
 *
 * Returns 0 on success. On failure it returns non-zero AND records a fault
 * envelope readable through `cbm_astro_env_fault_code()` /
 * `cbm_astro_env_fault_message()` / `cbm_astro_env_fault_remediation()`; the
 * previous override (if any) is left untouched.
 */
int cbm_astro_set_cache_dir(const char *path);

/* Drop any explicit override, restoring the CBM_CACHE_DIR/$HOME precedence. */
void cbm_astro_clear_cache_dir(void);

/*
 * The active explicit override, or NULL when none is set. The returned pointer
 * addresses process-lifetime static storage.
 */
const char *cbm_astro_cache_dir_override(void);

/* ── Fail-closed environment fault record (#241) ─────────────────── */

/*
 * Record a {code, message, remediation} store-configuration fault against
 * variable `var`. Emits the envelope exactly once per distinct (code, var) pair,
 * through CBM's log sink and on stderr — a refusal must remain visible when the
 * host silences logging, and the store resolvers are called per operation, so a
 * refusal that repeats on every call would be noise rather than signal.
 */
void cbm_astro_env_record_fault(const char *code, const char *var, const char *message,
                                const char *remediation);

/*
 * Record that reading environment variable `name` needed `needed` bytes but the
 * destination buffer holds only `capacity`. Raises CBM_E_ENV_VALUE_TRUNCATED.
 */
void cbm_astro_env_record_truncation(const char *name, size_t needed, size_t capacity);

/*
 * Record that no store could be resolved at all: no explicit override, no
 * CBM_CACHE_DIR, and no HOME/USERPROFILE. Raises CBM_E_STORE_UNRESOLVABLE, which
 * is what turns the vendored resolvers' bare `return NULL` into a labeled
 * degradation rather than a silent one (standing invariant 3).
 */
void cbm_astro_env_record_unresolvable_store(void);

/* Non-zero when the current fault (if any) was raised for `name`. */
int cbm_astro_env_faulted_for(const char *name);

/* Fault accessors. `cbm_astro_env_fault_code()` returns NULL when healthy. */
const char *cbm_astro_env_fault_code(void);
const char *cbm_astro_env_fault_message(void);
const char *cbm_astro_env_fault_remediation(void);

/* Clear the fault record. Used by tests and by a host that has remediated. */
void cbm_astro_env_fault_clear(void);

#endif /* ASTROLABE_CBM_ENV_STORE_CONFIG_H */
